### ISSUE TITLE
刻度尺未设置初值，0刻度为什么在dom的中间

### ISSUE THREAD

**Issue by jingyuLin1999** [zhouxianjun/vue-virtual-ruler#12]
<virtual-ruler
            ref="ruler"
            class="canvas-header"
            top-border
            :max="2500"
            :gap="10"
            :height="40"
            :value-gap="1"
            :default-value="300"
          />

**Comment by zhouxianjun** [comment]
可以给一个codepen地址吗

**Comment by jingyuLin1999** [comment]
感谢回复。
引用组件进来什么也没写，给你截个图，比较直观我的问题：
![image](https://user-images.githubusercontent.com/30433062/125742520-bafa3908-178b-4003-8c98-0aabf2ccad4c.png)

**Comment by zhouxianjun** [comment]
不好意思，有点忙，因为 point在中间。所以0在开始的地方，如果0不在开始的地方，那开始这个value可能就是其他值了，不是0了

**Comment by zhouxianjun** [comment]
你如果有时间，可以提交pr。支持这种类型。我目前没有时间去适配这种情况- -
