### ISSUE TITLE
valueGap为小数时，setValue失效问题

### ISSUE THREAD

**Issue by masterX89** [zhouxianjun/vue-virtual-ruler#17]
对于函数 `setValue` ：
```js
setValue (value) {
  this._setValue(value / this.valueGap);
},
```
如果 `valueGap` 为小数，且 `setValue` 中的 `value` 为小数时，`/` 操作可能得到意料外的数字。如 `value = 0.6`，`valueGap = 0.1` 的情况，`0.6 / 0.1` 得到 `5.999999999999999` 而非 `6`，则无法滚动到对应刻度。如下示例，点击按钮后，无法滚动到对应刻度。
```html
<button @click="$refs.ruler.setValue(0.6)">设置</button>
<virtual-ruler
  ref="ruler"
  top-border
  :height="50"
  :min="0"
  :max="2500"
  :default-value="v2"
  :gap="10"
  :value-gap="0.1"
  @change="v2 = $event"
/>
```
是否考虑针对 `[0,1]` 范围的 `valueGap` 使用 `Math.ceil(value / this.valueGap)` ?
若确认该问题存在，我可以提交对应 `pr`

**Comment by zhouxianjun** [comment]
确实存在小数精度问题，你提pr吧
